language: elixir

elixir: 1.9.0
otp_release: 22.0

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
  - sudo service postgresql restart

script:
  - mix test