language: elixir

elixir:
  - 1.6.1

addons:
  postgresql: '0.0.0'

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix test