language: elixir

elixir:
  - 1.6.1

otp_release:
  - 20.0

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - psql -c "CREATE DATABASE my_app_test;" -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'postgres';" -U postgres

script:
  - mix test